spring:
  config:
    import:
      "optional:classpath:/.secret.properties"
  profiles:
    active: demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
vaadin:
  url-mapping: /gui/*

org:
  novomax:
    llm:
      integration:
        ui:
          searchOneMapping:
            "[com.springchat.demo.entity.Candidate]": /gui/candidate-detail/{0}
logging:
  level:
    com:
      springchat: debug
    org:
      springframework: info
      apache:
        hc:
          client5: info
      novomax: debug


